### ISSUE TITLE
determinePreferredLanguage and messageformat's "Plural Function not found"

### ISSUE THREAD

**Issue by phw** [angular-translate/bower-angular-translate-interpolation-messageformat#10]
When using `determinePreferredLanguage()` together with angular-translate-interpolation-messageformat and the user has set an unsupported locale in the browser an "Plural Function not found" error is thrown by messageformat.

I think angular-translate-interpolation-messageformat should not just try to intitialize messageformat with any language but limit it to those languages registered with the `$translateProvider`. Otherwise this combination easily breaks, unless you include every possible pluralization rule for messageformat and even then there might be some users with unsupported languages.

I am not sure whether this should be fixed here or in `determinePreferredLanguage` (having `determinePreferredLanguage` not return any languages not registered with the `$translateProvider`) . Currently I work around it by using a custom `determinePreferredLanguage` which discards unsupported languages.

**Comment by knalli** [comment]
Please file any issues and bugs in our main repository at angular-translate/angular-translate.
