### ISSUE TITLE
Disable issues for this repository

### ISSUE THREAD

**Issue by phw** [angular-translate/bower-angular-translate-interpolation-messageformat#13]
As stated in the Readme all issues should be filed against the main angular-translate repository. Since you don't use it you should just disable the issues feature. This prevents wrongly filed bugs that nobody notices and reduces user and developer frustration :)

Issues can be disabled in the GitHub repository settiings

**Comment by knalli** [comment]
@phw  Yeah, I'm doing this right now. Should have been done much earlier..
