### ISSUE TITLE
Lock messageformat version at 0.1.6 (or upgrade to 0.2.x)

### ISSUE THREAD

**Issue by thomas88** [angular-translate/bower-angular-translate-interpolation-messageformat#5]
There is an issue with version 0.1.8 of messageformat.js, as you can read here https://github.com/SlexAxton/messageformat.js/issues/49. It would make sense to lock dependencies here to 0.1.6 or upgrade to version 0.2.x of messageformat.js.

**Comment by floriangosse** [comment]
+1

**Comment by knalli** [comment]
We appreciate any contributions for the messageformat adapter, at least we (the team) are not all-day users of that library.

What issue you are talking here? What would be a fix for translate?

Although the resulting dependencies will actually land in this repository, we are maintaining all issues in the main repository *angular-translate*. Please raise again an issue if you still think we have a todo. And even better: create a pull request! :dancers: 

Personally or from a operational view of point, I strongly recommend you not using such transient library updates you are not aware of. If it is fully semver compatibility.. well, it is an option. But auto-requiring code you have never seen, tested or checked is really bad. Therefor, you should stick to a messageformat version *you* have defined.. either an older one, or even a new one.
