### ISSUE TITLE
MessageFormat: `count` isnt a number

### ISSUE THREAD

**Issue by pascalmouret** [angular-translate/bower-angular-translate-interpolation-messageformat#8]
Hi, when updating to 2.7.2 we've encountered a problem with the type checking. When we have something like this: 

```html
<span translate="comment-count" translate-value-count="{{ comments.count }}"></span>
```

With a translation like this

```messageformat
{count, plural, one {one comment} other {\# comments}}
```

We get those `isnt a number` errors. After a bit of digging it seems that on the first iteration angular-translate tries to interpolate with `{{ comments.count }}` instead of the actual value.
Further iterations work fine, it just seems to happen on the first pass.

I've downgraded to 2.7.0 for now which seems to fix the problem for the moment.

**Comment by tspaeth** [comment]
Thanks for your report. Could you please - as written in the Readme file the defect in our main repository here: https://github.com/angular-translate/angular-translate/issues

Thanks.
